FROM node:20-alpine3.20 as BUILD

WORKDIR /app

# Copy dependency files
COPY webphim/package*.json ./

COPY webphim .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]