FROM node:20-alpine3.20

WORKDIR /app

# Copy dependency files
COPY webphim/package*.json ./
RUN npm run build
COPY webphim .

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]