apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: react-app 
  type: LoadBalancer #Type of the Kubernetes Service4
  ipFamilies:
    - IPv4
    - IPv6
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 #The port for the React.js application container
    nodePort: 30001