securityContext:
  runAsNonRoot: true
  fsGroup: 2000

service:
  type: ClusterIP

dashboardsProvider:
  enabled: true

dashboardsConfigMaps:
  - name: grafana-dashboard-k8s
    namespace: monitoring

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []